apiVersion: app/v1
kind: Deployment
metadata:
   name: my-react-app-depl
spec:
  replicas: 1
  selector:
     matcheslabel:
        app: react-app
  template:
    metadata:
      label:
        app: react-app
    spec:
    - containers:
        name: react-app
        image: dockername/react-app:v1
        app : react-app          
        
apiversion: app-srv/v1
kind: Service
metadata:
   name: my-react-app-srv
spec:
  type: NodePort
  selector:
     app: react-app
  ports:
  - name: my-react-app
    port: 3000 
    NodePort: 3000   

